version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: arcademmo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  server:
    build:
      context: ./server
      dockerfile: ../Dockerfile.server
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "4000:4000"
    volumes:
      - ./server:/usr/src/app
    command: npm run dev

  client:
    build:
      context: ./client
      dockerfile: ../Dockerfile.client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/usr/src/app
    command: npm run dev

volumes:
  pgdata:
