version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: arcademmo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redisdata:/data

  server:
    image: yourrepo/arcademmo-server:latest
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: production
    ports:
      - "80:4000"
    depends_on:
      - db
      - redis

volumes:
  pgdata:
  redisdata:
